apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: apps
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32410
  selector:
    app: myapp
